// Deterministic contract generation. No network, no model calls.
//   bun scripts/codegen.ts            -> writes generated/
//   bun scripts/codegen.ts <outDir>   -> writes elsewhere (used by check-drift)
//   bun scripts/codegen.ts <outDir> <registry.json>
//                                     -> same, from another registry file (used by the contract
//                                        tests to prove that an invalid registry fails generation)
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import Ajv2020 from "ajv/dist/2020";
import standaloneCode from "ajv/dist/standalone";
import { compile } from "json-schema-to-typescript";

const root = resolve(import.meta.dirname, "..");
const schemaDir = join(root, "contracts/schemas");
const outDir = resolve(process.argv[2] ?? join(root, "generated"));
const banner =
	"// GENERATED by scripts/codegen.ts from contracts/. Do not edit. Run `bun run codegen`.\n";

const files = readdirSync(schemaDir)
	.filter((f) => f.endsWith(".schema.json"))
	.sort();
const schemas = files.map((f) =>
	JSON.parse(readFileSync(join(schemaDir, f), "utf8")),
);
const registry = JSON.parse(
	readFileSync(
		resolve(process.argv[3] ?? join(root, "contracts/operations.json")),
		"utf8",
	),
);

// ---- validators (Ajv standalone, strict) ----
const ajv = new Ajv2020({
	strict: true,
	allErrors: true,
	code: { source: true, esm: true, lines: true },
});
for (const s of schemas) ajv.addSchema(s);

const exportName = (ref: string) =>
	ref.includes("#/$defs/")
		? (ref.split("#/$defs/")[1] as string)
		: (schemas.find((s) => s.$id === ref)?.title as string);

const validatorRefs: Record<string, string> = {};
for (const s of schemas) {
	if (s.type === "object" || s.oneOf) validatorRefs[s.title] = s.$id;
	if (s.$id === "requests.schema.json")
		for (const k of Object.keys(s.$defs))
			validatorRefs[k] = `${s.$id}#/$defs/${k}`;
}
const envelopeKinds: string[] = schemas.find(
	(s) => s.$id === "envelope.schema.json",
).properties.kind.enum;
for (const op of registry.operations) {
	const isEnvelope = op.response === "envelope.schema.json";
	if (isEnvelope && !envelopeKinds.includes(op.envelopeKind))
		throw new Error(
			`${op.operationId}: envelope response needs envelopeKind in [${envelopeKinds}]`,
		);
	if (!isEnvelope && op.envelopeKind !== undefined)
		throw new Error(
			`${op.operationId}: envelopeKind is only valid on envelope responses`,
		);
}
for (const op of registry.operations)
	for (const ref of [op.request, op.response, op.entries].filter(Boolean))
		if (!ajv.getSchema(ref))
			throw new Error(`${op.operationId}: unresolved schema ref ${ref}`);

const sortedRefs = Object.fromEntries(
	Object.entries(validatorRefs).sort(([a], [b]) => a.localeCompare(b)),
);
// Ajv standalone emits CommonJS `require("ajv/dist/runtime/<name>").default` even in ESM mode.
// A bare require is not safe in Convex or browser bundles, so hoist each one into an ESM import.
// The runtime files are CommonJS with `exports.default = fn`: Node's ESM interop hands back the
// module.exports object, while bundlers honouring __esModule hand back fn itself. Accept both.
const runtimeRequire =
	/^const (\w+) = require\("(ajv\/dist\/runtime\/\w+)"\)\.default;$/gm;
const runtimeImports: string[] = [];
const standaloneEsm = standaloneCode(ajv, sortedRefs).replace(
	runtimeRequire,
	(_line, local: string, specifier: string) => {
		runtimeImports.push(`import ${local}_mod from "${specifier}.js";\n`);
		return `const ${local} = typeof ${local}_mod === "function" ? ${local}_mod : ${local}_mod.default;`;
	},
);
const validatorsJs = banner + runtimeImports.sort().join("") + standaloneEsm;
if (validatorsJs.includes("require("))
	throw new Error(
		"codegen: generated validators still contain require(); extend the runtime import rewrite",
	);
const validatorsDts = `${banner}import type { ErrorObject } from "ajv";
export interface Validator { (data: unknown): boolean; errors?: ErrorObject[] | null }
${Object.keys(sortedRefs)
	.map((n) => `export declare const ${n}: Validator;`)
	.join("\n")}
`;

// ---- types (one bundle so shared definitions are declared once) ----
const bundle = {
	title: "ThinkWideContract",
	type: "object",
	additionalProperties: false,
	properties: Object.fromEntries(
		Object.entries(sortedRefs).map(([name, ref]) => [name, { $ref: ref }]),
	),
};
const types = await compile(bundle as never, "ThinkWideContract", {
	cwd: schemaDir,
	bannerComment: banner.trim(),
	additionalProperties: false,
	unreachableDefinitions: false,
	format: false,
	strictIndexSignatures: true,
});

// ---- operations ----
const EFFECTS = ["read", "state", "external"] as const;
const handlerPattern = /^[A-Za-z][A-Za-z0-9_/]*:[A-Za-z_$][A-Za-z0-9_$]*$/;
const ops = registry.operations.map((op: Record<string, unknown>) => ({
	...op,
	requestType: exportName(op.request as string),
	responseType: exportName(op.response as string),
	entriesType: op.entries ? exportName(op.entries as string) : null,
}));
const seenIds = new Set<string>();
const seenHandlers = new Map<string, string>();
for (const op of ops) {
	if (seenIds.has(op.operationId))
		throw new Error(`${op.operationId}: duplicate operationId`);
	seenIds.add(op.operationId);
	if (!EFFECTS.includes(op.effect))
		throw new Error(`${op.operationId}: effect must be one of [${EFFECTS}]`);
	if (!op.requestType || !op.responseType)
		throw new Error(`${op.operationId}: request/response has no named type`);
	if (op.handler === undefined) continue;
	if (typeof op.handler !== "string" || !handlerPattern.test(op.handler))
		throw new Error(
			`${op.operationId}: handler must be "<convexModule>:<exportName>"`,
		);
	const other = seenHandlers.get(op.handler);
	if (other)
		throw new Error(
			`${op.operationId}: handler ${op.handler} is already bound to ${other}`,
		);
	seenHandlers.set(op.handler, op.operationId);
}

type Json = Record<string, unknown>;
const isObject = (v: unknown): v is Json =>
	typeof v === "object" && v !== null && !Array.isArray(v);

// ---- UI templates (MCP Apps views) ----
// A template is a static ui:// resource. An operation binds one with `ui: { template }`. Both
// shapes are closed: an unknown key, an unknown template, a non-ui:// URI or a binding on an
// operation that is not MCP-exposed fails generation, the same way an unresolved schema ref does.
const MCP_APP_MIME_TYPE = "text/html;profile=mcp-app";
const templateName = /^[a-z][a-z0-9-]{0,63}$/;
const templateUri = /^ui:\/\/think-wide\/[a-z0-9][a-z0-9._-]{0,127}$/;
const exactKeys = (value: unknown, keys: string[], what: string) => {
	if (!isObject(value)) throw new Error(`${what}: must be an object`);
	const unknown = Object.keys(value).filter((k) => !keys.includes(k));
	if (unknown.length)
		throw new Error(`${what}: unknown properties [${unknown}]`);
	for (const k of keys)
		if (typeof value[k] !== "string" || value[k] === "")
			throw new Error(`${what}: ${k} must be a non-empty string`);
	return value as Record<string, string>;
};
const uiTemplates = new Map<string, Record<string, string>>();
if (registry.uiTemplates !== undefined) {
	if (!isObject(registry.uiTemplates))
		throw new Error("uiTemplates: must be an object");
	const seenUris = new Set<string>();
	for (const [name, value] of Object.entries(registry.uiTemplates)) {
		if (!templateName.test(name))
			throw new Error(`uiTemplates.${name}: invalid template name`);
		const template = exactKeys(
			value,
			["uri", "title", "description"],
			`uiTemplates.${name}`,
		);
		if (!templateUri.test(template.uri as string))
			throw new Error(
				`uiTemplates.${name}: uri must match ${templateUri.source}`,
			);
		if (seenUris.has(template.uri as string))
			throw new Error(`uiTemplates.${name}: duplicate uri`);
		seenUris.add(template.uri as string);
		uiTemplates.set(name, template);
	}
}
const boundTemplates = new Set<string>();
for (const op of ops) {
	if (op.ui === undefined) continue;
	const { template } = exactKeys(op.ui, ["template"], `${op.operationId}: ui`);
	if (!uiTemplates.has(template as string))
		throw new Error(`${op.operationId}: unknown ui template ${template}`);
	if (!(op.exposure as string[]).includes("mcp"))
		throw new Error(
			`${op.operationId}: ui is only valid on an MCP-exposed operation`,
		);
	boundTemplates.add(template as string);
}
for (const name of uiTemplates.keys())
	if (!boundTemplates.has(name))
		throw new Error(`uiTemplates.${name}: not bound by any operation`);

// Registry order everywhere, so output is a pure function of contracts/.
const typeMap = (name: string, field: "requestType" | "responseType") =>
	`export type ${name} = {\n${ops
		.map((o: Record<string, string>) => `\t${o.operationId}: ${o[field]};`)
		.join("\n")}\n};`;
const effectUnion = (name: string, effect: string) => {
	const ids = ops
		.filter((o: Record<string, string>) => o.effect === effect)
		.map((o: Record<string, string>) => JSON.stringify(o.operationId));
	return `export type ${name} = ${ids.length ? ids.join(" | ") : "never"};`;
};
const importedTypes = [
	...new Set(
		ops.flatMap((o: Record<string, string>) => [o.requestType, o.responseType]),
	),
].sort() as string[];
const unimplemented = ops
	.filter((o: Record<string, unknown>) => o.handler === undefined)
	.map((o: Record<string, string>) => o.operationId);
const operationsTs = `${banner}import type {
${importedTypes.map((t) => `\t${t},`).join("\n")}
} from "./types";

export const CONTRACT_VERSION = ${JSON.stringify(registry.contractVersion)} as const;

export const OPERATIONS = ${JSON.stringify(ops, null, "\t")} as const;

export type OperationId = (typeof OPERATIONS)[number]["operationId"];
export type EffectClass = "read" | "state" | "external";
export const MCP_EXPOSED: readonly OperationId[] = OPERATIONS.filter((o) =>
	(o.exposure as readonly string[]).includes("mcp"),
).map((o) => o.operationId);

/** Request and response type of every registered operation, from requestType / responseType. */
${typeMap("OperationRequestMap", "requestType")}
${typeMap("OperationResponseMap", "responseType")}

/** Operation ids by effect class. */
${effectUnion("ReadOperationId", "read")}
${effectUnion("StateOperationId", "state")}
${effectUnion("ExternalOperationId", "external")}

/** "<convexModule>:<exportName>" of the Convex function implementing each operation. */
export const OPERATION_HANDLERS = ${JSON.stringify(
	Object.fromEntries(
		ops
			.filter((o: Record<string, unknown>) => o.handler !== undefined)
			.map((o: Record<string, string>) => [o.operationId, o.handler]),
	),
	null,
	"\t",
)} as const;
export type ImplementedOperationId = keyof typeof OPERATION_HANDLERS;

/** Registered operations with no handler binding yet. */
export const UNIMPLEMENTED_OPERATIONS = ${JSON.stringify(unimplemented, null, "\t")} as const satisfies readonly OperationId[];
`;

// ---- MCP tool descriptors (pure data; the server and transport are T08) ----
// Each inputSchema is the operation's request schema bundled into one self-contained object:
// every transitively referenced definition is hoisted into the root `$defs` under a stable name
// and every `$ref` becomes `#/$defs/<Name>`. Recursion stays a ref. Validation keywords are
// copied verbatim; only `$id`, `$schema` and the nested `$defs` of a hoisted target are dropped.
const SUBSCHEMA = new Set(
	"items additionalProperties not if then else contains propertyNames unevaluatedItems unevaluatedProperties".split(
		" ",
	),
);
const SUBSCHEMA_LIST = new Set(["oneOf", "anyOf", "allOf", "prefixItems"]);
const SUBSCHEMA_MAP = new Set(
	"properties patternProperties dependentSchemas".split(" "),
);
const schemaFile = (file: string): Json => {
	const found = schemas.find((s) => s.$id === file);
	if (!found) throw new Error(`mcp bundle: unknown schema file ${file}`);
	return found;
};
const bundleSchema = (entryRef: string): Json => {
	const defs = new Map<string, unknown>();
	const owner = new Map<string, string>(); // def name -> absolute ref that claimed it
	const hoist = (ref: string, baseFile: string): string => {
		const [filePart = "", pointer = ""] = ref.split("#");
		const file = filePart || baseFile;
		const segments = pointer
			.split("/")
			.slice(1)
			.map((p) => p.replaceAll("~1", "/").replaceAll("~0", "~"));
		// file -> its title; file#/$defs/X -> X; any other pointer -> <Title>_<segments>.
		const name =
			segments.length === 2 && segments[0] === "$defs"
				? (segments[1] as string)
				: [schemaFile(file).title, ...segments].join("_");
		if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(name))
			throw new Error(`mcp bundle: cannot derive a $defs name for ${ref}`);
		const absolute = `${file}#${pointer}`;
		const claimed = owner.get(name);
		if (claimed !== undefined && claimed !== absolute)
			throw new Error(`mcp bundle: $defs name ${name} is ambiguous`);
		if (claimed === undefined) {
			owner.set(name, absolute); // claim before descending, so recursion terminates
			let target: unknown = schemaFile(file);
			for (const seg of segments)
				target = isObject(target) ? target[seg] : undefined;
			if (!isObject(target))
				throw new Error(`mcp bundle: ${ref} does not resolve to a schema`);
			defs.set(name, rewrite(target, file, true));
		}
		return `#/$defs/${name}`;
	};
	const rewrite = (node: unknown, file: string, isTarget = false): unknown => {
		if (!isObject(node)) return node; // boolean schema
		const out: Json = {};
		for (const [key, value] of Object.entries(node)) {
			if (isTarget && ["$id", "$schema", "$defs"].includes(key)) continue;
			if (key === "$ref" && typeof value === "string")
				out[key] = hoist(value, file);
			else if (SUBSCHEMA.has(key)) out[key] = rewrite(value, file);
			else if (SUBSCHEMA_LIST.has(key) && Array.isArray(value))
				out[key] = value.map((v) => rewrite(v, file));
			else if (SUBSCHEMA_MAP.has(key) && isObject(value))
				out[key] = Object.fromEntries(
					Object.entries(value).map(([k, v]) => [k, rewrite(v, file)]),
				);
			else if (key.startsWith("$") && key !== "$comment")
				throw new Error(`mcp bundle: unsupported keyword ${key} in ${file}`);
			else out[key] = structuredClone(value); // annotations and plain validation keywords
		}
		return out;
	};
	const [entryFile = "", entryPointer = ""] = entryRef.split("#");
	let entry: unknown = schemaFile(entryFile);
	for (const seg of entryPointer.split("/").slice(1))
		entry = isObject(entry) ? entry[seg] : undefined;
	const body = rewrite(entry, entryFile, true) as Json;
	// MCP requires a top-level `type: "object"`. Adding it is only faithful when every branch of a
	// top-level union already demands an object, so that nothing the real validator accepts is lost.
	if (body.type !== "object") {
		const branches = body.oneOf ?? body.anyOf;
		if (
			body.type !== undefined ||
			!Array.isArray(branches) ||
			!branches.every((b) => isObject(b) && b.type === "object")
		)
			throw new Error(`mcp bundle: ${entryRef} is not an object schema`);
	}
	const { title, description, type: _type, ...rest } = body;
	const sortedDefs = Object.fromEntries(
		[...defs].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
	);
	return {
		...(title === undefined ? {} : { title }),
		...(description === undefined ? {} : { description }),
		type: "object",
		...rest,
		...(defs.size ? { $defs: sortedDefs } : {}),
	};
};
// A bound tool carries the MCP Apps link (`_meta.ui.resourceUri`) and the ChatGPT compatibility
// alias for the same URI. An unbound tool has no `_meta` at all.
const uiToolMeta = (ui: { template: string } | undefined) => {
	if (ui === undefined) return {};
	const uri = uiTemplates.get(ui.template)?.uri;
	return {
		_meta: { ui: { resourceUri: uri }, "openai/outputTemplate": uri },
	};
};
// One static resource per template. No CSP origins: the views load nothing and connect nowhere.
const mcpUiResources = [...uiTemplates].map(([template, t]) => ({
	template,
	uri: t.uri,
	name: template,
	title: t.title,
	description: t.description,
	mimeType: MCP_APP_MIME_TYPE,
	_meta: {
		ui: {
			csp: { connectDomains: [], resourceDomains: [] },
			prefersBorder: true,
		},
	},
}));
const mcpTools = ops
	.filter((o: Record<string, unknown>) =>
		(o.exposure as string[]).includes("mcp"),
	)
	.map((o: Record<string, string | undefined>) => ({
		name: o.operationId,
		description: o.summary,
		operationId: o.operationId,
		effect: o.effect,
		handler: o.handler ?? null,
		inputSchema: bundleSchema(o.request as string),
		...uiToolMeta(o.ui as { template: string } | undefined),
	}));
// Fail generation, not a later adapter, if a bundle is not self-contained under strict Ajv.
for (const tool of mcpTools)
	new Ajv2020({ strict: true, allErrors: true }).compile(tool.inputSchema);
const mcpToolsTs = `${banner}// MCP tool descriptors: one per operation whose exposure includes "mcp", in registry order.
// Data only. inputSchema is the request schema bundled self-contained (refs are all #/$defs/...).
import type { OperationId } from "./operations";

export const MCP_TOOLS = ${JSON.stringify(mcpTools, null, "\t")} as const;

export const MCP_TOOL_NAMES = ${JSON.stringify(
	mcpTools.map((t: { name: string | undefined }) => t.name),
	null,
	"\t",
)} as const satisfies readonly OperationId[];
export type McpToolName = (typeof MCP_TOOL_NAMES)[number];

/** MIME type of an MCP Apps view (SEP-1865). ChatGPT renders the same type. */
export const MCP_APP_MIME_TYPE = ${JSON.stringify(MCP_APP_MIME_TYPE)} as const;

/** Static ui:// view resources, one per registry uiTemplate. \`template\` names the HTML source. */
export const MCP_UI_RESOURCES = ${JSON.stringify(mcpUiResources, null, "\t")} as const;
export type McpUiTemplate = (typeof MCP_UI_RESOURCES)[number]["template"];
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "validators.js"), validatorsJs);
writeFileSync(join(outDir, "validators.d.ts"), validatorsDts);
writeFileSync(join(outDir, "types.ts"), types);
writeFileSync(join(outDir, "operations.ts"), operationsTs);
writeFileSync(join(outDir, "mcp-tools.ts"), mcpToolsTs);
console.log(
	`codegen: ${files.length} schemas, ${Object.keys(sortedRefs).length} validators, ${ops.length} operations, ${mcpTools.length} MCP tools -> ${outDir}`,
);
