// Human-readable operation table, derived from generated/operations.ts. Nothing here is authored.
//   bun scripts/operations-doc.ts            -> prints Markdown to stdout
//   bun scripts/operations-doc.ts --write    -> writes docs/OPERATIONS.md
// scripts/check-drift.ts fails the gate when docs/OPERATIONS.md differs from this output.
import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { CONTRACT_VERSION, OPERATIONS } from "../generated/operations.ts";

const cell = (value: string) =>
	value.replaceAll("|", "\\|").replaceAll("\n", " ");
const code = (value: string) => `\`${value}\``;

const header = [
	"operationId",
	"effect",
	"exposure",
	"profile",
	"handler",
	"ui",
	"ticket",
	"summary",
];
const rows = OPERATIONS.map((o) => [
	code(o.operationId),
	o.effect,
	o.exposure.join(", "),
	o.profile,
	"handler" in o ? code(o.handler) : "unimplemented",
	"ui" in o ? code(o.ui.template) : "",
	o.ticket,
	o.summary,
]);
const implemented = OPERATIONS.filter((o) => "handler" in o).length;

const markdown = `# Operations

GENERATED by \`scripts/operations-doc.ts\` from \`generated/operations.ts\` (source: \`contracts/operations.json\`). Do not edit. Run \`bun scripts/operations-doc.ts --write\`; \`bun run verify\` fails when this file is stale.

Contract ${CONTRACT_VERSION} · ${OPERATIONS.length} operations · ${implemented} implemented · ${OPERATIONS.length - implemented} unimplemented

\`handler\` is \`<convexModule>:<exportName>\`. \`read\` operations are Convex queries, \`state\` operations are mutations with a receipt. An operation is agent-exposed only if \`mcp\` is in its exposure. \`ui\` names the read-only MCP Apps view template an MCP host may render for the tool result.

| ${header.join(" | ")} |
|${header.map(() => "---").join("|")}|
${rows.map((r) => `| ${r.map(cell).join(" | ")} |`).join("\n")}
`;

if (process.argv.includes("--write")) {
	const target = join(resolve(import.meta.dirname, ".."), "docs/OPERATIONS.md");
	writeFileSync(target, markdown);
	console.log(`operations doc: wrote ${target}`);
} else process.stdout.write(markdown);
