/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as HandoffsHandoffIdRouteImport } from './routes/handoffs.$handoffId'
import { Route as InvestigationsInvestigationIdRouteImport } from './routes/investigations.$investigationId'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiOpsOperationIdRouteImport } from './routes/api/ops.$operationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffsHandoffIdRoute = HandoffsHandoffIdRouteImport.update({
  id: '/handoffs/$handoffId',
  path: '/handoffs/$handoffId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsInvestigationIdRoute =
  InvestigationsInvestigationIdRouteImport.update({
    id: '/investigations/$investigationId',
    path: '/investigations/$investigationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsOperationIdRoute = ApiOpsOperationIdRouteImport.update({
  id: '/api/ops/$operationId',
  path: '/api/ops/$operationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workshop': typeof WorkshopRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/mcp': typeof ApiMcpRoute
  '/handoffs/$handoffId': typeof HandoffsHandoffIdRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/ops/$operationId': typeof ApiOpsOperationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workshop': typeof WorkshopRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/mcp': typeof ApiMcpRoute
  '/handoffs/$handoffId': typeof HandoffsHandoffIdRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/ops/$operationId': typeof ApiOpsOperationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workshop': typeof WorkshopRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/mcp': typeof ApiMcpRoute
  '/handoffs/$handoffId': typeof HandoffsHandoffIdRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/ops/$operationId': typeof ApiOpsOperationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workshop'
    | '/.well-known/oauth-protected-resource'
    | '/api/mcp'
    | '/handoffs/$handoffId'
    | '/investigations/$investigationId'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/ops/$operationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workshop'
    | '/.well-known/oauth-protected-resource'
    | '/api/mcp'
    | '/handoffs/$handoffId'
    | '/investigations/$investigationId'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/ops/$operationId'
  id:
    | '__root__'
    | '/'
    | '/workshop'
    | '/.well-known/oauth-protected-resource'
    | '/api/mcp'
    | '/handoffs/$handoffId'
    | '/investigations/$investigationId'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/ops/$operationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkshopRoute: typeof WorkshopRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiMcpRoute: typeof ApiMcpRoute
  HandoffsHandoffIdRoute: typeof HandoffsHandoffIdRoute
  InvestigationsInvestigationIdRoute: typeof InvestigationsInvestigationIdRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiOpsOperationIdRoute: typeof ApiOpsOperationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoffs/$handoffId': {
      id: '/handoffs/$handoffId'
      path: '/handoffs/$handoffId'
      fullPath: '/handoffs/$handoffId'
      preLoaderRoute: typeof HandoffsHandoffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$investigationId': {
      id: '/investigations/$investigationId'
      path: '/investigations/$investigationId'
      fullPath: '/investigations/$investigationId'
      preLoaderRoute: typeof InvestigationsInvestigationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/$operationId': {
      id: '/api/ops/$operationId'
      path: '/api/ops/$operationId'
      fullPath: '/api/ops/$operationId'
      preLoaderRoute: typeof ApiOpsOperationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkshopRoute: WorkshopRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiMcpRoute: ApiMcpRoute,
  HandoffsHandoffIdRoute: HandoffsHandoffIdRoute,
  InvestigationsInvestigationIdRoute: InvestigationsInvestigationIdRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiOpsOperationIdRoute: ApiOpsOperationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
